#!/usr/bin/env bash

# Check user environment variable
if [[ -z "${PROJECT_ID}" ]]; then
  echo "Missing PROJECT_ID environment variable" >&2
  exit 1
fi

if [[ -z "${PORT}" ]]; then
  echo "Missing PORT environment variable" >&2
  exit 1
fi

# Config gcloud project
gcloud config set project ${PROJECT_ID}

# Start emulator
gcloud beta emulators pubsub start \
  --data-dir=/opt/data \
  --host-port=0.0.0.0:${PORT}